id: 5868e4478c7a4ce19e165c0e02f330f1
initial_creation_type: ocr
source_metadata:
  volumes:
    370079b0038e4663949b378e9cea7d9d:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: ཁ་ཏོན་དང་གླེགས་བམ་ཀླག་པའི་སྔོན་དུ་བྱ་བའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
